--------------------------------------------------------
--  File created - Saturday-May-22-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APPOINTMENTS
--------------------------------------------------------

  CREATE TABLE "DAS"."APPOINTMENTS" 
   (	"ID" NUMBER(*,0), 
	"STATUS" VARCHAR2(9 BYTE), 
	"PRESCRIPTION" VARCHAR2(255 BYTE), 
	"PATIENT_ID" NUMBER(*,0), 
	"DOCTOR_ID" NUMBER(*,0), 
	"SCHED_ID" NUMBER(*,0), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SCHEDULES
--------------------------------------------------------

  CREATE TABLE "DAS"."SCHEDULES" 
   (	"ID" NUMBER(*,0), 
	"DAY" VARCHAR2(9 BYTE), 
	"START_TIME" VARCHAR2(255 BYTE), 
	"END_TIME" VARCHAR2(255 BYTE), 
	"DOCTOR_ID" NUMBER(*,0), 
	"DATE_CREATED" DATE, 
	"STATUS" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "DAS"."USERS" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"CONTACT_NO" VARCHAR2(255 BYTE), 
	"ROLE" VARCHAR2(7 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"JOINED" DATE, 
	"AGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index APPOINTMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DAS"."APPOINTMENTS_PK" ON "DAS"."APPOINTMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SCHEDULES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DAS"."SCHEDULES_PK" ON "DAS"."SCHEDULES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DAS"."USERS_PK" ON "DAS"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger APPOINTMENTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DAS"."APPOINTMENTS_TRG" 
BEFORE INSERT ON APPOINTMENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DAS"."APPOINTMENTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger APPOINTMENTS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DAS"."APPOINTMENTS_TRG1" 
BEFORE INSERT ON APPOINTMENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT APPOINTMENTS_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DAS"."APPOINTMENTS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SCHEDULES_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DAS"."SCHEDULES_TRG1" 
BEFORE INSERT ON SCHEDULES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DAS"."SCHEDULES_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SCHEDULES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DAS"."SCHEDULES_TRG" 
BEFORE INSERT ON SCHEDULES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DAS"."SCHEDULES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DAS"."USERS_TRG" 
BEFORE INSERT ON USERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DAS"."USERS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DAS"."USERS_TRG1" 
BEFORE INSERT ON USERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DAS"."USERS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_TRG2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DAS"."USERS_TRG2" 
BEFORE INSERT ON USERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DAS"."USERS_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_TRG3
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DAS"."USERS_TRG3" 
BEFORE INSERT ON USERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT USERS_SEQ3.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DAS"."USERS_TRG3" ENABLE;
--------------------------------------------------------
--  Constraints for Table APPOINTMENTS
--------------------------------------------------------

  ALTER TABLE "DAS"."APPOINTMENTS" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "DAS"."APPOINTMENTS" MODIFY ("SCHED_ID" NOT NULL ENABLE);
  ALTER TABLE "DAS"."APPOINTMENTS" MODIFY ("DOCTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "DAS"."APPOINTMENTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DAS"."APPOINTMENTS" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "DAS"."APPOINTMENTS" ADD CONSTRAINT "STATUS_CHECK" CHECK (STATUS in('BOOKED','CANCELLED','COMPLETED')) ENABLE;
  ALTER TABLE "DAS"."APPOINTMENTS" ADD CONSTRAINT "APPOINTMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DAS"."APPOINTMENTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SCHEDULES
--------------------------------------------------------

  ALTER TABLE "DAS"."SCHEDULES" ADD CONSTRAINT "STATUS_TYPE" CHECK (status in('ACTIVE','RESERVED')) ENABLE;
  ALTER TABLE "DAS"."SCHEDULES" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "DAS"."SCHEDULES" MODIFY ("DOCTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "DAS"."SCHEDULES" MODIFY ("END_TIME" NOT NULL ENABLE);
  ALTER TABLE "DAS"."SCHEDULES" MODIFY ("START_TIME" NOT NULL ENABLE);
  ALTER TABLE "DAS"."SCHEDULES" MODIFY ("DAY" NOT NULL ENABLE);
  ALTER TABLE "DAS"."SCHEDULES" ADD CONSTRAINT "TYPE_CHECK" CHECK (DAY in('SUNDAY','MONDAY','TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY')) ENABLE;
  ALTER TABLE "DAS"."SCHEDULES" ADD CONSTRAINT "SCHEDULES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DAS"."SCHEDULES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "DAS"."USERS" MODIFY ("JOINED" NOT NULL ENABLE);
  ALTER TABLE "DAS"."USERS" ADD CONSTRAINT "CON_TYPE" CHECK (ROLE in('PATIENT','DOCTOR','ADMIN')) ENABLE;
  ALTER TABLE "DAS"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DAS"."USERS" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "DAS"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "DAS"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "DAS"."USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "DAS"."USERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table APPOINTMENTS
--------------------------------------------------------

  ALTER TABLE "DAS"."APPOINTMENTS" ADD CONSTRAINT "FK_DOCTOR_USER_ID" FOREIGN KEY ("DOCTOR_ID")
	  REFERENCES "DAS"."USERS" ("ID") ENABLE;
  ALTER TABLE "DAS"."APPOINTMENTS" ADD CONSTRAINT "FK_PATIENT_USER_ID" FOREIGN KEY ("PATIENT_ID")
	  REFERENCES "DAS"."USERS" ("ID") ENABLE;
  ALTER TABLE "DAS"."APPOINTMENTS" ADD CONSTRAINT "FK_SCHED_ID" FOREIGN KEY ("SCHED_ID")
	  REFERENCES "DAS"."SCHEDULES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCHEDULES
--------------------------------------------------------

  ALTER TABLE "DAS"."SCHEDULES" ADD CONSTRAINT "FK_DOCTOR_SCHED_ID" FOREIGN KEY ("DOCTOR_ID")
	  REFERENCES "DAS"."USERS" ("ID") ENABLE;
